name: "FactSnap"
environment: "local"

server:
  port: "8080"
  baseUrl: "api"

postgres:
  host: "localhost"
  port: "5432"
  user: "user"
  password: "pw"
  name: "server-db"
  sslmode: "disable"

clerk:
  secretKey:

uploadthing:
  appId:
  secretKey:
  baseUrl: "https://api.uploadthing.com" # optional, defaults to https://api.uploadthing.com
  cdnBaseUrl: "https://utfs.io/f" # optional, defaults to https://utfs.io/f